[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools",
    "numpy>=1.20",
    "GPUtil==1.4",
]

[project]
name = "cuBNM"
version = "0.0.1"
license = {file = "LICENSE"}
dependencies = [
    "numpy>=1.20",
    "GPUtil==1.4",
    "scipy",
    "pandas",
    "pymoo==0.6",
    "scikit-optimize==0.9",
]
requires-python = ">=3.7"
description = "A toolbox for biophysical network modeling on GPUs "
readme = "README.md"
authors = [
    {name = "Amin Saberi", email="amnsbr@gmail.com"}
]
classifiers = [
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Science/Research',
    'Intended Audience :: Developers',
    'Programming Language :: C',
    'Programming Language :: C++',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3 :: Only',
    'Operating System :: Unix',
    'Environment :: GPU :: NVIDIA CUDA',
    'Topic :: Scientific/Engineering',
]

[tool.setuptools]
include-package-data = true

[tool.cibuildwheel]
manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"
manylinux-ppc64le-image = "manylinux_2_28"
before-all = "bash {project}/tools/cibw_before_all.sh"
build-verbosity = 3
skip = ["pp*", "*-manylinux_i686", "*musllinux*"]